# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js
    - /local/hass-crypto-icons.js

logger:
  default: info
  logs:
    custom_components.cryptoinfo_advanced: debug


# Text to speech
tts:
  - platform: google_translate

# Helper to keep the start time
input_datetime:
  device_start_time:
    name: Device Start Time
    has_time: true
    has_date: false
  device_end_time:
    name: Device End Time
    has_time: true
    has_date: false

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
mqtt: !include mqtt.yaml
influxdb: !include influxdb.yaml
notify: !include notify.yaml
shell_command: !include shell.yaml

light:
  - platform: group
    name: Living Room Lights
    entities:
      - light.signify_netherlands_b_v_lta004_huelight_2
      - light.signify_netherlands_b_v_lta004_huelight_3
      - light.signify_netherlands_b_v_lta004_huelight_4

python_script:

sensor: !include sensors.yaml

http:
  ssl_certificate: /etc/letsencrypt/live/ha.auroranrunner.com/fullchain.pem
  ssl_key: /etc/letsencrypt/live/ha.auroranrunner.com/privkey.pem

homeassistant:
  external_url: !secret external_url
  customize: !include customize.yaml

recorder:
  db_url: !secret db_url

# Create states directory
shell_command:
  create_states_dir: "mkdir -p /config/ha_states"

# Run on startup
automation startup_automation:
  alias: "Create States Directory"
  trigger:
    platform: homeassistant
    event: start
  action:
    service: shell_command.create_states_dir
