sensor:
  - name: "Temperature Living Room"
    state_topic: "shellies/shellyht-70757F/sensor/temperature"
    value_template: "{{ value | float | round(1) }}"
    unit_of_measurement: "째C"
    device_class: "temperature"
    unique_id: "temperature_living_room"

  - name: "Humidity Living Room"
    state_topic: "shellies/shellyht-70757F/sensor/humidity"
    value_template: "{{ value | float }}"
    unit_of_measurement: "%"
    device_class: "humidity"
    unique_id: "humidity_living_room"

  - name: "Battery Living Room"
    state_topic: "shellies/shellyht-70757F/sensor/battery"
    value_template: "{{ value | float }}"
    unit_of_measurement: "%"
    device_class: "battery"
    unique_id: "battery_living_room"

  - name: "Temperature Bedroom"
    state_topic: "shellies/shellyht-70849A/sensor/temperature"
    value_template: "{{ value | float | round(1) }}"
    unit_of_measurement: "째C"
    device_class: "temperature"
    unique_id: "temperature_bedroom"

  - name: "Humidity Bedroom"
    state_topic: "shellies/shellyht-70849A/sensor/humidity"
    value_template: "{{ value | float }}"
    unit_of_measurement: "%"
    device_class: "humidity"
    unique_id: "humidity_bedroom"

  - name: "Battery Bedroom"
    state_topic: "shellies/shellyht-70849A/sensor/battery"
    value_template: "{{ value | float | round(7) }}"
    unit_of_measurement: "%"
    device_class: "battery"
    unique_id: "battery_bedroom"

  - name: "Temperature Seestymishuone"
    state_topic: "shellies/shellyht-023DEF/sensor/temperature"
    value_template: "{{ value | float | round(1) }}"
    unit_of_measurement: "째C"
    device_class: "temperature"
    unique_id: "temperature_seestymis"

  - name: "Humidity Seestysmistuone"
    state_topic: "shellies/shellyht-023DEF/sensor/humidity"
    value_template: "{{ value | float }}"
    unit_of_measurement: "%"
    device_class: "humidity"
    unique_id: "humidity_seestymis"

  - name: "Battery Seestymishuone"
    state_topic: "shellies/shellyht-023DEF/sensor/battery"
    value_template: "{{ value | float }}"
    unit_of_measurement: "%"
    device_class: "battery"
    unique_id: "battery_seestymis"

  - name: "Temperature Tapio's Office"
    state_topic: "shellies/shellyht-707C09/sensor/temperature"
    value_template: "{{ value | float | round(1) }}"
    unit_of_measurement: "째C"
    device_class: "temperature"
    unique_id: "temperature_office"
    force_update: true

  - name: "Humidity Tapio's Office"
    state_topic: "shellies/shellyht-707C09/sensor/humidity"
    value_template: "{{ value | float }}"
    unit_of_measurement: "%"
    device_class: "humidity"
    unique_id: "humidity_office"

  - name: "Battery Tapio's Office"
    state_topic: "shellies/shellyht-707C09/sensor/battery"
    value_template: "{{ value | float }}"
    unit_of_measurement: "%"
    device_class: "battery"
    unique_id: "battery_office"

  - name: "Binance LTC Balance"
    state_topic: "binance/balance_ltc"
    value_template: "{{ value | float }}" 
    unit_of_measurement: "LTC"
    unique_id: "binance_balance_ltc"

  - name: "Binance DOGE Balance"
    state_topic: "binance/balance_doge"
    value_template: "{{ value | float }}" 
    unit_of_measurement: "DOGE"
    unique_id: "binance_balance_doge"

  - name: "Binance PEPE Balance"
    state_topic: "binance/balance_pepe"
    value_template: "{{ value | float }}" 
    unit_of_measurement: "PEPE"
    unique_id: "binance_balance_pepe"

  - name: "Binance BTC Balance"
    state_topic: "binance/balance_btc"
    value_template: "{{ value | float }}" 
    unit_of_measurement: "BTC"
    unique_id: "binance_balance_btc"

  - name: "Binance XRP Balance"
    state_topic: "binance/balance_xrp"
    value_template: "{{ value | float }}" 
    unit_of_measurement: "XRP"
    unique_id: "binance_balance_xrp"

  - name: "Binance Total Balance in EUR"
    state_topic: "binance/balance_total_eur"
    value_template: "{{ value | float }}" 
    unit_of_measurement: "EUR"
    unique_id: "binance_balance_total_eur"

  - name: "Binance Total Balance in USD"
    state_topic: "binance/balance_total_usd"
    value_template: "{{ value | float }}" 
    unit_of_measurement: "USD"
    unique_id: "binance_balance_total_usd"

  - name: "Binance Total Balance in CAD"
    state_topic: "binance/balance_total_cad"
    value_template: "{{ value | float }}" 
    unit_of_measurement: "CAD"
    unique_id: "binance_balance_total_cad"

  - name: "Exodus LTC Balance"
    state_topic: "exodus/balance_ltc"
    value_template: "{{ value | float }}"
    unit_of_measurement: "LTC"
    unique_id: "exodus_balance_ltc"

  - name: "Exodus BTC Balance"
    state_topic: "exodus/balance_btc"
    value_template: "{{ value | float }}"
    unit_of_measurement: "BTC"
    unique_id: "exodus_balance_btc"

  - name: "Exodus DOGE Balance"
    state_topic: "exodus/balance_doge"
    value_template: "{{ value | float }}"
    unit_of_measurement: "DOGE"
    unique_id: "exodus_balance_doge"

  - name: "Exodus Total Balance in USD"
    state_topic: "exodus/balance_total_usd"
    value_template: "{{ value | float }}"
    unit_of_measurement: "USD"
    unique_id: "exodus_balance_total_usd"

  - name: "Exodus Total Balance in CAD"
    state_topic: "exodus/balance_total_cad"
    value_template: "{{ value | float }}"
    unit_of_measurement: "CAD"
    unique_id: "exodus_balance_total_cad"

  - name: "Exodus Total Balance in EUR"
    state_topic: "exodus/balance_total_eur"
    value_template: "{{ value | float }}"
    unit_of_measurement: "EUR"
    unique_id: "exodus_balance_total_eur"

  - name: "Kraken LTC Balance"
    state_topic: "kraken/balance_ltc"
    value_template: "{{ value | float }}"
    unit_of_measurement: "LTC"
    unique_id: "kraken_balance_ltc"

  - name: "Kraken DOGE Balance"
    state_topic: "kraken/balance_doge"
    value_template: "{{ value | float }}"
    unit_of_measurement: "DOGE"
    unique_id: "kraken_balance_doge"

  - name: "Kraken BTC Balance"
    state_topic: "kraken/balance_btc"
    value_template: "{{ value | float }}"
    unit_of_measurement: "BTC"
    unique_id: "kraken_balance_btc"

  - name: "Kraken PEPE Balance"
    state_topic: "kraken/balance_pepe"
    value_template: "{{ value | float }}"
    unit_of_measurement: "PEPE"
    unique_id: "kraken_balance_pepe"

  - name: "Kraken Total Balance in CAD"
    state_topic: "kraken/balance_total_cad"
    value_template: "{{ value | float }}"
    unit_of_measurement: "CAD"
    unique_id: "kraken_balance_total_cad"

  - name: "Kraken Balance Total USD"
    state_topic: "kraken/balance_total_usd"
    value_template: "{{ value | float }}"
    unit_of_measurement: "USD"
    unique_id: "kraken_balance_total_usd"

  - name: "Kraken Balance Total EUR"
    state_topic: "kraken/balance_total_eur"
    value_template: "{{ value | float }}"
    unit_of_measurement: "EUR"
    unique_id: "kraken_balance_total_eur"

  - name: "Litewallet LTC Balance"
    state_topic: "litewallet/balance_ltc"
    value_template: "{{ value | float }}"
    unit_of_measurement: "LTC"
    unique_id: "litewallet_balance_ltc"

  - name: "Litewallet Total Balance CAD"
    state_topic: "litewallet/balance_total_cad"
    value_template: "{{ value | float }}"
    unit_of_measurement: "CAD"
    unique_id: "litewallet_balance_total_cad"

  - name: "Litewallet Balance Total USD"
    state_topic: "litewallet/balance_total_usd"
    value_template: "{{ value | float }}"
    unit_of_measurement: "USD"
    unique_id: "litewallet_balance_total_usd"

  - name: "Litewallet Balance Total EUR"
    state_topic: "litewallet/balance_total_eur"
    value_template: "{{ value | float }}"
    unit_of_measurement: "EUR"
    unique_id: "litewallet_balance_total_eur"

  - name: "Crypto Coin Value LTC"
    state_topic: "cryptocoin/value_ltc"
    value_template: "{{ value | float }}"
    unit_of_measurement: "USD"
    unique_id: "cryptocoin_value_ltc"

  - name: "Crypto Coin Value DOGE"
    state_topic: "cryptocoin/value_doge"
    value_template: "{{ value | float }}"
    unit_of_measurement: "USD"
    unique_id: "cryptocoin_value_doge"

  - name: "Crypto Coin Value BTC"
    state_topic: "cryptocoin/value_btc"
    value_template: "{{ value | float }}"
    unit_of_measurement: "USD"
    unique_id: "cryptocoin_value_btc"

  - name: "Crypto Coin Value ETH"
    state_topic: "cryptocoin/value_eth"
    value_template: "{{ value | float }}"
    unit_of_measurement: "USD"
    unique_id: "cryptocoin_value_eth"

  - name: "Crypto Coin Value XRP"
    state_topic: "cryptocoin/value_xrp"
    value_template: "{{ value | float }}"
    unit_of_measurement: "USD"
    unique_id: "cryptocoin_value_xrp"

  - name: "Crypto Coin Value XPM"
    state_topic: "cryptocoin/value_xpm"
    value_template: "{{ value | float }}"
    unit_of_measurement: "USD"
    unique_id: "cryptocoin_value_xpm"

  - name: "Crypto Coin Value SOL"
    state_topic: "cryptocoin/value_sol"
    value_template: "{{ value | float }}"
    unit_of_measurement: "USD"
    unique_id: "cryptocoin_value_sol"

  - name: "Crypto Coin Value SHIB"
    state_topic: "cryptocoin/value_shib"
    value_template: "{{ value | float }}"
    unit_of_measurement: "USD"
    unique_id: "cryptocoin_value_shib"

  - name: "Crypto Coin Value PEPE"
    state_topic: "cryptocoin/value_pepe"
    value_template: "{{ value | float }}"
    unit_of_measurement: "USD"
    unique_id: "cryptocoin_value_pepe"

  - name: "Crypto Coin Value BNB"
    state_topic: "cryptocoin/value_bnb"
    value_template: "{{ value | float }}"
    unit_of_measurement: "USD"
    unique_id: "cryptocoin_value_bnb"

  - name: "CAD in EUR"
    state_topic: "currency/cad_eur"
    value_template: "{{ value | float }}"
    unit_of_measurement: "EUR"
    unique_id: "currency_cad_eur"

  - name: "EUR in USD"
    state_topic: "currency/usd_eur"
    value_template: "{{ value | float }}"
    unit_of_measurement: "USD"
    unique_id: "currency_eur_usd"

  - name: "EUR in CAD"
    state_topic: "currency/eur_cad"
    value_template: "{{ value | float }}"
    unit_of_measurement: "CAD"
    unique_id: "currency_eur_cad"

  - name: "USD in EUR"
    state_topic: "currency/eur_usd"
    value_template: "{{ value | float }}"
    unit_of_measurement: "EUR"
    unique_id: "currency_usd_eur"

  - name: "Binance BNB Balance"
    state_topic: "binance/balance_bnb"
    value_template: "{{ value | float }}" 
    unit_of_measurement: "BNB"
    unique_id: "binance_balance_bnb"

  - name: "Binance LTC 2nd Balance"
    state_topic: "binance2/balance_ltc"
    value_template: "{{ value | float }}" 
    unit_of_measurement: "LTC"
    unique_id: "binance2_balance_ltc"

  - name: "Binance DOGE 2nd Balance"
    state_topic: "binance2/balance_doge"
    value_template: "{{ value | float }}" 
    unit_of_measurement: "DOGE"
    unique_id: "binance2_balance_doge"

  - name: "Binance PEPE 2nd Balance"
    state_topic: "binance2/balance_pepe"
    value_template: "{{ value | float }}" 
    unit_of_measurement: "PEPE"
    unique_id: "binance2_balance_pepe"

  - name: "Binance BTC 2nd Balance"
    state_topic: "binance2/balance_btc"
    value_template: "{{ value | float }}" 
    unit_of_measurement: "BTC"
    unique_id: "binance2_balance_btc"

  - name: "Binance XRP 2nd Balance"
    state_topic: "binance2/balance_xrp"
    value_template: "{{ value | float }}" 
    unit_of_measurement: "XRP"
    unique_id: "binance2_balance_xrp"

  - name: "Binance Total 2nd Balance in EUR"
    state_topic: "binance2/balance_total_eur"
    value_template: "{{ value | float }}" 
    unit_of_measurement: "EUR"
    unique_id: "binance2_balance_total_eur"

  - name: "Binance Total 2nd Balance in USD"
    state_topic: "binance2/balance_total_usd"
    value_template: "{{ value | float }}" 
    unit_of_measurement: "USD"
    unique_id: "binance2_balance_total_usd"

  - name: "Binance Total 2nd Balance in CAD"
    state_topic: "binance2/balance_total_cad"
    value_template: "{{ value | float }}" 
    unit_of_measurement: "CAD"
    unique_id: "binance2_balance_total_cad"

  - name: "Binance BNB 2nd  Balance"
    state_topic: "binance2/balance_bnb"
    value_template: "{{ value | float }}" 
    unit_of_measurement: "BNB"
    unique_id: "binance2_balance_bnb"

  - name: "Binance ETH 2nd  Balance"
    state_topic: "binance2/balance_eth"
    value_template: "{{ value | float }}" 
    unit_of_measurement: "ETH"
    unique_id: "binance2_balance_eth"

  - name: "Binance ETH Balance"
    state_topic: "binance/balance_eth"
    value_template: "{{ value | float }}" 
    unit_of_measurement: "ETH"
    unique_id: "binance_balance_eth"

  - name: "Exodus ETH Balance"
    state_topic: "exodus/balance_eth"
    value_template: "{{ value | float }}"
    unit_of_measurement: "ETH"
    unique_id: "exodus_balance_eth"

  - name: "Kraken ETH Balance"
    state_topic: "kraken/balance_eth"
    value_template: "{{ value | float }}"
    unit_of_measurement: "ETH"
    unique_id: "kraken_balance_eth"

  - name: "Binance ADA 2nd Balance"
    state_topic: "binance2/balance_ada"
    value_template: "{{ value | float }}" 
    unit_of_measurement: "ADA"
    unique_id: "binance2_balance_ada"

  - name: "Crypto Coin Value ADA"
    state_topic: "cryptocoin/value_ada"
    value_template: "{{ value | float }}"
    unit_of_measurement: "USD"
    unique_id: "cryptocoin_value_ada"

  - name: "Miner Hashrate"
    state_topic: "miner/hashrate"
    value_template: "{{ value | float }}"
    unit_of_measurement: "MH/s"
    device_class: "power"
    state_class: "measurement"
    unique_id: "miner_hashrate"  

  - name: "Miner Hashrate Efficiency"
    state_topic: "miner/hashrate_efficiency"
    value_template: "{{ value | float | round(1) }}"
    unit_of_measurement: "%"
    state_class: "measurement"
    unique_id: "miner_hashrate_efficiency"

  - name: "Miner Outlet Temperature 1"
    state_topic: "miner/outlet_temp1"
    value_template: "{{ value | float | round(1) }}"
    unit_of_measurement: "째C"
    device_class: "temperature"
    state_class: "measurement"
    unique_id: "miner_outlet_temp1"

  - name: "Miner Outlet Temperature 2"
    state_topic: "miner/outlet_temp2"
    value_template: "{{ value | float | round(1) }}"
    unit_of_measurement: "째C"
    device_class: "temperature"
    state_class: "measurement"
    unique_id: "miner_outlet_temp2"

  - name: "Miner Inlet Temperature 1"
    state_topic: "miner/inlet_temp1"
    value_template: "{{ value | float | round(1) }}"
    unit_of_measurement: "째C"
    device_class: "temperature"
    state_class: "measurement"
    unique_id: "miner_inlet_temp1"

  - name: "Miner Inlet Temperature 2"
    state_topic: "miner/inlet_temp2"
    value_template: "{{ value | float | round(1) }}"
    unit_of_measurement: "째C"
    device_class: "temperature"
    state_class: "measurement"
    unique_id: "miner_inlet_temp2"

  - name: "Miner Fan Speed"
    state_topic: "miner/fan_speed"
    value_template: "{{ value | float }}"
    unit_of_measurement: "RPM"
    device_class: "frequency"
    state_class: "measurement"
    unique_id: "miner_fan_speed"
